- name: Configure RHEL 9 Managed Node
  hosts: managed_nodes
  become: yes
  vars:
    managed_node_ip: "192.168.10.134"
    gateway_ip: "192.168.10.1"
    dns_servers: ["8.8.8.8", "8.8.4.4"]

  tasks:
    - name: Set static IP on managed node
      ansible.builtin.nmcli:
        conn_name: "{{ ansible_default_ipv4.interface }}"
        type: ethernet
        ip4: "{{ managed_node_ip }}/24"
        gw4: "{{ gateway_ip }}"
        dns4: "{{ dns_servers }}"
        state: present
        method4: manual
      when: ansible_default_ipv4.address != managed_node_ip

    - name: Ensure SSH service is running
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: yes

    - name: Display node configuration
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_fqdn }}"
          - "IP: {{ ansible_default_ipv4.address }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "SSH User: {{ ansible_user_id }}"
          - "SSH Port: {{ ansible_port | default(22) }}"